# Basic site configuration
title: Vizibal
description: Your site description
theme: jekyll-theme-minimal

# CORS configuration
defaults:
  - scope:
      path: "/"
    values:
      Access-Control-Allow-Origin: "*"
